/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesEndoscopicEarSurgeryRouteImport } from './routes/services.endoscopic-ear-surgery'
import { Route as ServicesEndoscopicSinusSurgeryRouteImport } from './routes/services.endoscopic-sinus-surgery'
import { Route as ServicesEntCareRouteImport } from './routes/services.ent-care'
import { Route as ServicesSnoringSleepApneaRouteImport } from './routes/services.snoring-sleep-apnea'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEndoscopicEarSurgeryRoute =
  ServicesEndoscopicEarSurgeryRouteImport.update({
    id: '/services/endoscopic-ear-surgery',
    path: '/services/endoscopic-ear-surgery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEndoscopicSinusSurgeryRoute =
  ServicesEndoscopicSinusSurgeryRouteImport.update({
    id: '/services/endoscopic-sinus-surgery',
    path: '/services/endoscopic-sinus-surgery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEntCareRoute = ServicesEntCareRouteImport.update({
  id: '/services/ent-care',
  path: '/services/ent-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSnoringSleepApneaRoute =
  ServicesSnoringSleepApneaRouteImport.update({
    id: '/services/snoring-sleep-apnea',
    path: '/services/snoring-sleep-apnea',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/appointment': typeof AppointmentRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/reviews': typeof ReviewsRoute
  '/services/endoscopic-ear-surgery': typeof ServicesEndoscopicEarSurgeryRoute
  '/services/endoscopic-sinus-surgery': typeof ServicesEndoscopicSinusSurgeryRoute
  '/services/ent-care': typeof ServicesEntCareRoute
  '/services/snoring-sleep-apnea': typeof ServicesSnoringSleepApneaRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/appointment': typeof AppointmentRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/reviews': typeof ReviewsRoute
  '/services/endoscopic-ear-surgery': typeof ServicesEndoscopicEarSurgeryRoute
  '/services/endoscopic-sinus-surgery': typeof ServicesEndoscopicSinusSurgeryRoute
  '/services/ent-care': typeof ServicesEntCareRoute
  '/services/snoring-sleep-apnea': typeof ServicesSnoringSleepApneaRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/appointment': typeof AppointmentRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/reviews': typeof ReviewsRoute
  '/services/endoscopic-ear-surgery': typeof ServicesEndoscopicEarSurgeryRoute
  '/services/endoscopic-sinus-surgery': typeof ServicesEndoscopicSinusSurgeryRoute
  '/services/ent-care': typeof ServicesEntCareRoute
  '/services/snoring-sleep-apnea': typeof ServicesSnoringSleepApneaRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/gallery'
    | '/appointment'
    | '/blogs'
    | '/contact'
    | '/reviews'
    | '/services/endoscopic-ear-surgery'
    | '/services/endoscopic-sinus-surgery'
    | '/services/ent-care'
    | '/services/snoring-sleep-apnea'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gallery'
    | '/appointment'
    | '/blogs'
    | '/contact'
    | '/reviews'
    | '/services/endoscopic-ear-surgery'
    | '/services/endoscopic-sinus-surgery'
    | '/services/ent-care'
    | '/services/snoring-sleep-apnea'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/gallery'
    | '/appointment'
    | '/blogs'
    | '/contact'
    | '/reviews'
    | '/services/endoscopic-ear-surgery'
    | '/services/endoscopic-sinus-surgery'
    | '/services/ent-care'
    | '/services/snoring-sleep-apnea'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GalleryRoute: typeof GalleryRoute
  AppointmentRoute: typeof AppointmentRoute
  BlogsRoute: typeof BlogsRoute
  ContactRoute: typeof ContactRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesEndoscopicEarSurgeryRoute: typeof ServicesEndoscopicEarSurgeryRoute
  ServicesEndoscopicSinusSurgeryRoute: typeof ServicesEndoscopicSinusSurgeryRoute
  ServicesEntCareRoute: typeof ServicesEntCareRoute
  ServicesSnoringSleepApneaRoute: typeof ServicesSnoringSleepApneaRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/endoscopic-ear-surgery': {
      id: '/services/endoscopic-ear-surgery'
      path: '/services/endoscopic-ear-surgery'
      fullPath: '/services/endoscopic-ear-surgery'
      preLoaderRoute: typeof ServicesEndoscopicEarSurgeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/endoscopic-sinus-surgery': {
      id: '/services/endoscopic-sinus-surgery'
      path: '/services/endoscopic-sinus-surgery'
      fullPath: '/services/endoscopic-sinus-surgery'
      preLoaderRoute: typeof ServicesEndoscopicSinusSurgeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ent-care': {
      id: '/services/ent-care'
      path: '/services/ent-care'
      fullPath: '/services/ent-care'
      preLoaderRoute: typeof ServicesEntCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/snoring-sleep-apnea': {
      id: '/services/snoring-sleep-apnea'
      path: '/services/snoring-sleep-apnea'
      fullPath: '/services/snoring-sleep-apnea'
      preLoaderRoute: typeof ServicesSnoringSleepApneaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GalleryRoute: GalleryRoute,
  AppointmentRoute: AppointmentRoute,
  BlogsRoute: BlogsRoute,
  ContactRoute: ContactRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesEndoscopicEarSurgeryRoute: ServicesEndoscopicEarSurgeryRoute,
  ServicesEndoscopicSinusSurgeryRoute: ServicesEndoscopicSinusSurgeryRoute,
  ServicesEntCareRoute: ServicesEntCareRoute,
  ServicesSnoringSleepApneaRoute: ServicesSnoringSleepApneaRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
